############################################################################
############################################################################
##  Document Path: includes/body/data/server.R
##
##  Description: Handler for all data imported or generated by the app for
##  use in exploratory data analysis
##
##  R version 4.4.1 (2024-06-14 ucrt)
##
#############################################################################
#############################################################################


originalData <- reactive({
  mtcars
})

originalData2 <- reactive({
  if (is.null(input$fileupd)) {
    updateDirStatus4("No dataset was uploaded.")
    data.frame()
  } else {
    GLOBAL$data.orig.filename <- input$fileupd["name"]
    read.csv(input$fileupd$datapath, header = 1L)
  }
})

dataV2 <- reactive({
  if (input$checkGroupDatasetT == 1) {
    ordata <- originalData()
  } else {
    ordata <- originalData2()
  }

  tryCatch(eval(parse(text = paste0("subset(ordata,", input$subsetting1, ")"))),
    error = function(e) ordata[1, ]
  )
})

dataV3 <- reactive({
  if (input$checkGroupDatasetT == 1) {
    ordata <- originalData()
  } else {
    ordata <- originalData2()
  }

  tryCatch(eval(parse(text = paste0("subset(ordata,", input$subsetting2, ")"))),
    error = function(e) ordata[1, ]
  )
})


observeEvent(input$rundatabutton, {
  ordata <- originalData()
  if (input$checkGroupDatasetT == 2) {
    if (is.null(input$fileupd)) {
      updateDirStatus4("No dataset was uploaded.")
    } else {
      ordata <- originalData2()
    }
  }
  GLOBAL$data.versions.filter <- list(
    "original" = "",
    "dataV2" = input$subsetting1,
    "dataV3" = input$subsetting2
  )

  GLOBAL$data.versions <- list(
    "original" = ordata,
    "dataV2" = dataV2(),
    "dataV3" = dataV3()
  )
})

output$rhstable1 <- renderDT(
  switch(input$datatoUseV1,
    "original" = GLOBAL$data.versions$original,
    "dataV2" = GLOBAL$data.versions$dataV2,
    "dataV3" = GLOBAL$data.versions$dataV3
  ),
  options = list(lengthChange = FALSE), filter = list(position = "top")
)



observeEvent(input$checkGroupDatasetT, {
  if (input$checkGroupDatasetT == 1) {
    updateDirStatus4("Sample dataset will be generated. Specify the sample size.")
  } else {
    updateDirStatus4("Select a csv dataset with headers to upload.")
  }
})


observe({
  if (input$checkGroupDatasetT == 1) {
    updateVariableHolder(paste(names(originalData()), collapse = " "))
  } else {
    updateVariableHolder(paste(names(originalData2()), collapse = " "))
  }
})

observeEvent(input$shwvarnames, {
  shinyjs::toggleClass("varnamesholder", class = "hider")
})



output$rhstable1summary <- renderPrint({
  summary.data.frame(switch(input$datatoUseV1,
    "original" = GLOBAL$data.versions$original,
    "dataV2" = GLOBAL$data.versions$dataV2,
    "dataV3" = GLOBAL$data.versions$dataV3
  ))
})

output$subj1summary <- renderPrint({
  "Provide unempty dataset, or fill Variable Matching tab"
  plot.data <- (switch(input$datatoUseV1,
    "original" = GLOBAL$data.versions$original,
    "dataV2" = GLOBAL$data.versions$dataV2,
    "dataV3" = GLOBAL$data.versions$dataV3
  ))

  if (!length(plot.data)) {
    return("Provide unempty dataset, or fill Variable Matching tab")
  }
  if (is.null(plot.data) | input$idvar == "" | input$cfacetvar == "") {
    return("Provide unempty dataset, or fill Variable Matching tab")
  }


  d2 <- data.frame(
    Description = c(
      paste0("Number of subjects in ", input$datatoUseV1, " data version"),
      paste0("Number of treatments in ", input$datatoUseV1, " data version"),
      paste0("Total number of records in ", input$datatoUseV1, " data version")
    ),
    Statistic = c(
      length(unique(plot.data[[input$idvar]])),
      length(unique(plot.data[[input$cfacetvar]])),
      length(plot.data[[input$cfacetvar]])
    )
  )


  flextable(d2) %>%
    theme_vanilla() %>%
    # theme_apa() %>%
    autofit() %>%
    htmltools_value()
})
