message(this.path)
messageappabout = HTML("
<h2>Please read to understand if this app may be useful for your QC needs</h2>
<p>After preparing report outputs, an analyst may be required to conduct quality control (QC) on another analyst's work. </p><p>During this process, the QC analyst reviews the scripts used to generate the outputs to identify any potential errors. </p>If errors are found, the QC analyst will highlight them for correction. If no errors are detected, the QC analyst will typically regenerate all outputs and compare them against those produced by the original analyst to ensure accuracy. This application facilitates the QC process by allowing analysts to easily verify their outputs against those generated by the original script creator.
")
observeEvent(input$aboutproject, {
  showModal(modalDialog(
    title = "About this app",
    messageappabout
  ))
})

observeOnce(
  {
    showModal(modalDialog(
      title = "About this app",
      messageappabout
    ))
  },
  input = input,
  output = output
)
